# Generated by Django 5.0.1 on 2024-02-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
